[variables]
NIXPACKS_POETRY_VERSION = "2.0.1"

[phases.setup]
nixPkgs = ["...", "poetry"]
aptPkgs = ["...", "build-essential", "libpq-dev", "postgresql-client"]

[phases.install]
cmds = ['python -m venv --copies /opt/venv && . /opt/venv/bin/activate && poetry install --with prod --no-interaction --no-ansi']

[phases.release]
dependsOn = ["install"]
cmds = ["python manage.py migrate && python manage.py collectstatic --no-input && python manage.py compress"]

[start]
cmd = "gunicorn config.wsgi --bind 0.0.0.0:8000"
