# Generated by Django 5.1.2 on 2024-10-17 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="asset",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="warranty",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="warranty_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="asset",
            name="warranty_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="warranty_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="asset",
            name="warranty_provider",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="warranty",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="warranty_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="warranty_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="warranty_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="warranty_provider",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="asset",
            name="make",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="make",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="assets.manufacturer",
            ),
        ),
    ]
