# Generated by Django 5.1.2 on 2024-11-04 21:31

from django.db import migrations
from django.apps.registry import Apps
from slugify import slugify


def set_manufacturer_slugs(apps: Apps, schema_editor):
    Manufacturer = apps.get_model("assets", "Manufacturer")
    for manufacturer in Manufacturer.objects.all():
        manufacturer.slug = slugify(manufacturer.name)
        manufacturer.save()


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_manufacturer_slug_alter_manufacturer_name"),
    ]

    operations = [
        migrations.RunPython(
            set_manufacturer_slugs, reverse_code=migrations.RunPython.noop
        ),
    ]
