# Generated by Django 5.1.2 on 2024-11-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_set_manufacturer_slugs"),
        ("locations", "0004_delete_containerattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.location",
            ),
        ),
    ]
