# Generated by Django 5.1.2 on 2024-10-21 18:18

import django.db.models.deletion
import homebin.attachments.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("attachments", "0001_initial"),
        ("attachments", "0002_alter_attachment_type_and_more"),
        ("attachments", "0003_alter_attachment_type_and_more"),
        ("attachments", "0004_alter_attachment_type_and_more"),
        ("attachments", "0005_alter_attachment_type_and_more"),
        ("attachments", "0006_alter_attachment_type_and_more"),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "attachment",
                    models.FileField(
                        upload_to=homebin.attachments.models.attachment_upload_to
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GenericAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=homebin.attachments.models.attachment_upload_to
                    ),
                ),
                ("name", models.CharField(editable=False, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("sort_rank", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_rank"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="attachments_content_c34382_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAttachment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("attachment", models.TextField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Attachment",
                "verbose_name_plural": "historical Attachments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
