# Generated by Django 5.1.2 on 2024-10-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0003_alter_attachment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="genericattachment",
            name="attachment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalattachment",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                default="image",
                max_length=10,
            ),
        ),
    ]
