# Generated by Django 5.1.2 on 2024-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0004_alter_attachment_type_and_more"),
    ]

    operations = []
