# Generated by Django 5.1.2 on 2024-10-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0007_move_attachments_to_generic_attachments"),
        ("locations", "0004_delete_containerattachment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attachment",
        ),
        migrations.DeleteModel(
            name="HistoricalAttachment",
        ),
    ]
