# Generated by Django 5.1.2 on 2024-10-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0008_delete_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("document", "Document"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                ],
                default="image",
                max_length=10,
            ),
        ),
    ]
