# Generated by Django 5.1.2 on 2024-10-16 19:07

import django.db.models.deletion
import homebin.locations.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attachments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default=homebin.locations.models.default_container_label,
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "container_description",
                    models.CharField(
                        max_length=100,
                        verbose_name="description of container; e.g. 'black w/ yellow lid'",
                    ),
                ),
                (
                    "simple_contents",
                    models.TextField(
                        blank=True, verbose_name="simple description of contents"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContainerAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("rank", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containers",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_attachments",
                        to="locations.container",
                    ),
                ),
            ],
            options={
                "verbose_name": "Container Attachment",
                "verbose_name_plural": "Container Attachments",
                "ordering": ["container", "attachment"],
            },
        ),
        migrations.AddField(
            model_name="container",
            name="attachments",
            field=models.ManyToManyField(
                through="locations.ContainerAttachment", to="attachments.attachment"
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Location",
                "verbose_name_plural": "historical Locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContainer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        db_index=True,
                        default=homebin.locations.models.default_container_label,
                        max_length=25,
                    ),
                ),
                (
                    "container_description",
                    models.CharField(
                        max_length=100,
                        verbose_name="description of container; e.g. 'black w/ yellow lid'",
                    ),
                ),
                (
                    "simple_contents",
                    models.TextField(
                        blank=True, verbose_name="simple description of contents"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical container",
                "verbose_name_plural": "historical containers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="container",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containers",
                to="locations.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="containerattachment",
            constraint=models.UniqueConstraint(
                fields=("container", "attachment"), name="unique_container_attachment"
            ),
        ),
        migrations.AddConstraint(
            model_name="containerattachment",
            constraint=models.UniqueConstraint(
                fields=("container", "rank"), name="unique_container_rank"
            ),
        ),
    ]
