# Generated by Django 5.1.2 on 2024-10-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="containerattachment",
            options={
                "ordering": ["rank", "container", "attachment"],
                "verbose_name": "Container Attachment",
                "verbose_name_plural": "Container Attachments",
            },
        ),
        migrations.RemoveConstraint(
            model_name="containerattachment",
            name="unique_container_rank",
        ),
        migrations.AlterField(
            model_name="containerattachment",
            name="rank",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
