# Generated by Django 5.1.2 on 2024-10-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_containerattachment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="attachments",
        ),
    ]
