# Generated by Django 5.1.2 on 2024-12-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_delete_containerattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="container_description",
            field=models.CharField(
                help_text="e.g. 'black w/ yellow lid'",
                max_length=100,
                verbose_name="description of container",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontainer",
            name="container_description",
            field=models.CharField(
                help_text="e.g. 'black w/ yellow lid'",
                max_length=100,
                verbose_name="description of container",
            ),
        ),
    ]
