# Generated by Django 5.1.2 on 2024-12-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_container_container_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
